GAMEDIR = nethackdir

CFLAGS = -g -fPIE -fstack-protector
CFLAGS+=-DCOMPRESS='"$(shell command -v gzip)"' -DCOMPRESS_EXTENSION='".gz"'
CFLAGS+=-DHACKDIR='"."'
CFLAGS+=-DCURSES_GRAPHICS -DCURSES_UNICODE
CFLAGS+=-DDUMPLOG
CFLAGS+=-D_XOPEN_SOURCE_EXTENDED # for wide char support in ncurses
LDFLAGS = -fPIE -pie

CPPFLAGS += -Iinclude
CPPFLAGS += -DDLB

.DELETE_ON_ERROR:

.PHONY: all
all: src/nethack util/recover dat/nhdat dat/license dat/symbols

.PHONY: install
install: all
	mkdir -p $(GAMEDIR)
	install src/nethack $(GAMEDIR)
	install util/recover $(GAMEDIR)
	install -m 644 dat/nhdat dat/license dat/symbols $(GAMEDIR)
	install -m 644 sys/unix/sysconf $(GAMEDIR)
	touch $(GAMEDIR)/perm
	touch $(GAMEDIR)/record
	touch $(GAMEDIR)/logfile
	touch $(GAMEDIR)/xlogfile
	touch $(GAMEDIR)/livelog
	mkdir -p $(GAMEDIR)/save
	sed -i 's/WIZARDS=.*/WIZARDS=\*/' $(GAMEDIR)/sysconf
	sed -i "s/^#DUMPLOGFILE=\/tmp\//DUMPLOGFILE=/" $(GAMEDIR)/sysconf
	#sed -i 's/PANICTRACE_GDB=1/PANICTRACE_GDB=2/' $(GAMEDIR)/sysconf

##### BINARIES #####

SRCOBJ = allmain.o alloc.o apply.o artifact.o attrib.o ball.o bones.o botl.o \
 calendar.o cfgfiles.o cmd.o coloratt.o date.o dbridge.o decl.o detect.o dig.o \
 display.o dlb.o do.o dog.o dogmove.o dokick.o do_name.o dothrow.o do_wear.o \
 drawing.o dungeon.o eat.o end.o engrave.o exper.o explode.o extralev.o files.o \
 fountain.o getpos.o glyphs.o hack.o hacklib.o insight.o invent.o isaac64.o \
 light.o lock.o mail.o makemon.o mcastu.o mdlib.o mhitm.o mhitu.o minion.o \
 mklev.o mkmap.o mkmaze.o mkobj.o mkroom.o mon.o mondata.o monmove.o monst.o \
 mplayer.o mthrowu.o muse.o music.o nhlobj.o nhlsel.o nhlua.o nhmd4.o objects.o \
 objnam.o o_init.o options.o pager.o pickup.o pline.o polyself.o potion.o pray.o \
 priest.o quest.o questpgr.o read.o rect.o region.o report.o restore.o rip.o \
 rnd.o role.o rumors.o save.o selvar.o sfbase.o sfstruct.o shk.o shknam.o sit.o \
 sounds.o spell.o sp_lev.o stairs.o steal.o steed.o strutil.o symbols.o sys.o \
 teleport.o timeout.o topten.o track.o trap.o uhitm.o u_init.o utf8map.o vault.o \
 version.o vision.o weapon.o were.o wield.o windows.o wizard.o wizcmds.o worm.o \
 worn.o write.o zap.o

SYSUNIXOBJ = unixmain.o unixres.o unixunix.o
SYSSHAREOBJ = ioctl.o posixregex.o unixtty.o
WINTTYOBJ = getline.o termcap.o topl.o wintty.o
WINCURSESOBJ = cursmain.o curswins.o cursmisc.o cursdial.o cursstat.o	\
               cursinit.o cursmesg.o cursinvt.o

GAME_O = $(SRCOBJ:%.o=src/%.o) $(SYSUNIXOBJ:%.o=sys/unix/%.o)	\
         $(SYSSHAREOBJ:%.o=sys/share/%.o)			\
         $(WINTTYOBJ:%.o=win/tty/%.o)				\
         $(WINCURSESOBJ:%.o=win/curses/%.o)
src/nethack: $(GAME_O)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -lncursesw -ltinfo $(LUA_DIR)/liblua.a -lm -ldl -o $@
AUTO_BIN += src/nethack

RECOVER_O = src/hacklib.o util/recover-version.o util/recover.o
util/recover: $(RECOVER_O)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
AUTO_BIN += util/recover

MAKEDEFS_O = src/hacklib.o src/date.o util/makedefs.o src/alloc.o src/monst.o src/objects.o	\
             util/panic.o
util/makedefs: $(MAKEDEFS_O)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
AUTO_BIN += util/makedefs

DLB_O = src/hacklib.o util/dlb_main.o src/alloc.o src/dlb.o util/panic.o
util/dlb: $(DLB_O)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
AUTO_BIN += util/dlb

DGN_COMP_O = util/dgn_main.o util/dgn_lex.o util/dgn_yacc.o	\
             src/alloc.o util/panic.o
util/dgn_comp: $(DGN_COMP_O)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
AUTO_BIN += util/dgn_comp

LEV_COMP_O = util/lev_main.o util/lev_lex.o util/lev_yacc.o	\
             src/alloc.o src/decl.o src/drawing.o src/monst.o	\
             src/objects.o util/panic.o
util/lev_comp: $(LEV_COMP_O)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
AUTO_BIN += util/lev_comp

TILEMAP_O = win/share/tilemap.o
util/tilemap: $(TILEMAP_O)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
AUTO_BIN += util/tilemap

ALL_O = $(GAME_O) $(RECOVER_O) $(MAKEDEFS_O) $(DLB_O) \
        $(TILEMAP_O)

##### BASIC RULES AND AUTOMATIC DEPENDENCY GENERATION #####

MAKEFLAGS += --no-builtin-rules
.SUFFIXES:

%.o: %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -MMD -MP -c -o $@ $<
util/recover-version.o: src/version.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -DMINIMAL_FOR_RECOVER -MMD -MP -c -o $@ $<

%.d:
	$(CC) $(CFLAGS) $(CPPFLAGS) -MM -MP -MG -MT $*.o -MF $@ $*.c

ALL_D = $(ALL_O:%.o=%.d)
-include $(ALL_D)

##### AUTOGENERATED SOURCE FILES #####

include/date.h: util/makedefs $(filter-out src/version.o,$(GAME_O))
	cd util && ./makedefs -v # include/date.h dat/options
include/onames.h: util/makedefs
	cd util && ./makedefs -o # include/onames.h
include/pm.h: util/makedefs
	cd util && ./makedefs -p # include/pm.h
AUTO_H += include/nhlua.h include/date.h include/onames.h include/pm.h

# generating the dependencies of source files requires them to exist,
# so the dependencies of the autogenerated source files have to be
# declared explicitly instead

src/monstr.c: util/makedefs
	cd util && ./makedefs -m  # src/monstr.c
AUTO_C += src/monstr.c

src/tile.c: util/tilemap
	cd util && ./tilemap  # src/tile.c
AUTO_C += src/tile.c

src/tile.o: include/onames.h include/pm.h

# for missing headers during the first automatic dependency generation
$(AUTO_H:include/%.h=%.h): %.h: include/%.h ;

# empty "bootstrap" dependency files are fine here, they'll be fixed
# during the first compilation
$(AUTO_C:%.c=%.d):
	touch $@

##### DATA FILES #####

QUEST_LUA = ???-goal.lua ???-fil?.lua ???-loca.lua ???-strt.lua

SPEC_LUA = asmodeus.lua baalz.lua bigrm-*.lua castle.lua fakewiz?.lua \
           juiblex.lua knox.lua medusa-?.lua minend-?.lua minefill.lua \
           minetn-?.lua oracle.lua orcus.lua sanctum.lua soko?-?.lua \
           tower?.lua valley.lua wizard?.lua nhcore.lua nhlib.lua themerms.lua \
           astral.lua air.lua earth.lua fire.lua water.lua hellfill.lua tut-?.lua

ALL_LUA = $(QUEST_LUA) $(SPEC_LUA)
ALL_TAG = $(ALL_LUA:%.lua=dat/%.lua)

DAT_NHDAT = cmdhelp data help hh history opthelp options \
            oracles rumors wizhelp bogusmon engrave epitaph
dat/nhdat: util/dlb $(DAT_NHDAT:%=dat/%) $(ALL_TAG)
	cd dat && ../util/dlb cf nhdat $(DAT_NHDAT) *.lua
AUTO_DAT += dat/nhdat

dat/data: dat/data.base util/makedefs
	cd util && ./makedefs -d # dat/data
dat/options: include/date.h # util/makedefs
#	cd util && ./makedefs -v # include/date.h dat/options
dat/oracles: dat/oracles.txt util/makedefs
	cd util && ./makedefs -h # dat/oracles
dat/rumors: dat/rumors.tru dat/rumors.fal util/makedefs
	cd util && ./makedefs -r # dat/rumors
AUTO_DAT += dat/data dat/options dat/oracles dat/rumors

dat/bogusmon: dat/engrave dat/bogusmon.txt util/makedefs
	cd util && ./makedefs -3 # dat/bogusmon
dat/engrave: dat/epitaph dat/engrave.txt util/makedefs
	cd util && ./makedefs -2 # dat/engrave
dat/epitaph: dat/epitaph.txt util/makedefs
	cd util && ./makedefs -1 # dat/epitaph
AUTO_DAT += dat/bogusmon dat/engrave dat/epitaph

LUA_VERSION ?=5.4.6
LUA_REPO = https://github.com/lua/lua.git
LUA_DIR = lib/lua-$(LUA_VERSION)

include/nhlua.h:
	if [ ! -d $(LUA_DIR) ]; then (git clone --branch v5.4 --single-branch $(LUA_REPO) $(LUA_DIR)); fi
	(cd $(LUA_DIR) && git checkout v$(LUA_VERSION))
	(cd $(LUA_DIR) && (env MAKEFLAGS= $(MAKE) SYSCFLAGS='-DLUA_USE_LINUX' all))
	@echo '/* nhlua.h - generated by Makefile */' > $@
	@echo '#include "../$(LUA_DIR)/lua.h"' >> $@
	@sed -e '/(lua_error)/!d' \
		-e '/(lua_error)/s/LUA_API/ATTRNORETURN LUA_API/1' \
		-e '/(lua_error)/s/;/ NORETURN;/1' < $(LUA_DIR)/lua.h >> $@
	@echo '#include "../$(LUA_DIR)/lualib.h"' >> $@
	@echo '#include "../$(LUA_DIR)/lauxlib.h"' >> $@
	@echo '/*nhlua.h*/' >> $@

##### CLEANING UP #####

.PHONY: clean
clean:
	rm -f $(AUTO_BIN)
	rm -f $(ALL_O)

	rm -f $(AUTO_H)
	rm -f $(AUTO_C)

	rm -f $(AUTO_DAT)

.PHONY: cleandeps
cleandeps: clean
	rm -f $(ALL_D)
